### ISSUE TITLE
Traffic Generation

### ISSUE THREAD

**Issue by neel-patel-1** [darchr/dram-cache-model#1]
Hello,

Very interesting work.

I was hoping to see if there was a traffic generation script allowing control over the miss ratio and  dirty or clean cache lines in case of misses. The traffic generator currently implements rd/wr ratio and random/linear patterns.

Was fig. 1 in "Enabling Design Space Exploration of DRAM Caches in Emerging Memory Systems" generated using a custom trace to get the desired dirty-miss ratios?

Thanks

**Comment by neel-patel-1** [comment]
It seems the relevant variables/parameters to toggle 100% hits/misses (dram_cache_ctrl.hh::alwaysHit) and 100% dirty/clean (dram_cache_ctrl.hh::alwaysDirty) should provide the data from fig. 1.

**Comment by mbabaie** [comment]
Hi Neel,

Thanks for reaching out and your question!

I guess you are talking about the figure 4 (instead of figure 1) in our arxiv paper: https://arxiv.org/pdf/2303.13029.pdf

That figure studies the **extreme** cases in terms of hit/miss and dirty/clean DRAM cache lines and it's been controlled by 2 flags in DRAM cache controller (the Policy Manager) **alwaysHit** and **alwaysDirty**. The type of traffic (linear, random, read or write percentage) is controlled by the traffic generator. We have not used a specific custom trace for that figure, though one may use any desired traces and feed it into our DRAM cache model.

If you have any questions, please let me know.

**Comment by neel-patel-1** [comment]
Hi Maryam,

I was talking about figure 4. Sorry for the confusion. 

Thanks for your explanation. I will reach out if I have any other questions.

Also, nice work on the DRAM cache model.

-Neel
